// <auto-generated />
using System;
using BackendAPP.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BackendAPP.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210723153448_MigrationPart1")]
    partial class MigrationPart1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.8");

            modelBuilder.Entity("BackendAPP.Models.Client", b =>
                {
                    b.Property<long>("Id_Client")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom_Client")
                        .HasColumnType("TEXT");

                    b.Property<string>("Presentation")
                        .HasColumnType("TEXT");

                    b.HasKey("Id_Client");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("BackendAPP.Models.ClientThematique", b =>
                {
                    b.Property<long>("Id_Client")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Id_Thematique")
                        .HasColumnType("TEXT");

                    b.Property<long?>("ThematiqueId_Thematique")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id_Client", "Id_Thematique");

                    b.HasIndex("ThematiqueId_Thematique");

                    b.ToTable("ClientThematiques");
                });

            modelBuilder.Entity("BackendAPP.Models.Pole", b =>
                {
                    b.Property<long>("Id_Pole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom_Pole")
                        .HasColumnType("TEXT");

                    b.HasKey("Id_Pole");

                    b.ToTable("Poles");
                });

            modelBuilder.Entity("BackendAPP.Models.Technologie", b =>
                {
                    b.Property<long>("Id_Techno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Libelle")
                        .HasColumnType("TEXT");

                    b.HasKey("Id_Techno");

                    b.ToTable("Technologies");
                });

            modelBuilder.Entity("BackendAPP.Models.Thematique", b =>
                {
                    b.Property<long>("Id_Thematique")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Image")
                        .HasColumnType("TEXT");

                    b.Property<string>("Libelle")
                        .HasColumnType("TEXT");

                    b.HasKey("Id_Thematique");

                    b.ToTable("Thematiques");
                });

            modelBuilder.Entity("BackendAPP.Models.ClientThematique", b =>
                {
                    b.HasOne("BackendAPP.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("Id_Client")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendAPP.Models.Thematique", "Thematique")
                        .WithMany()
                        .HasForeignKey("ThematiqueId_Thematique");

                    b.Navigation("Client");

                    b.Navigation("Thematique");
                });
#pragma warning restore 612, 618
        }
    }
}
