// <auto-generated />
using System;
using BackendAPP.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BackendAPP.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210723130645_MigrationForKey")]
    partial class MigrationForKey
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.8");

            modelBuilder.Entity("BackendAPP.Models.Client", b =>
                {
                    b.Property<long>("Id_Client")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom_Client")
                        .HasColumnType("TEXT");

                    b.Property<string>("Presentation")
                        .HasColumnType("TEXT");

                    b.HasKey("Id_Client");

                    b.ToTable("clients");
                });

            modelBuilder.Entity("BackendAPP.Models.ClientThematique", b =>
                {
                    b.Property<long>("Id_Client")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Id_thematique")
                        .HasColumnType("TEXT");

                    b.Property<long?>("thematiqueId_thematique")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id_Client", "Id_thematique");

                    b.HasIndex("thematiqueId_thematique");

                    b.ToTable("clientThematiques");
                });

            modelBuilder.Entity("BackendAPP.Models.Pole", b =>
                {
                    b.Property<long>("Id_Pole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom_Pole")
                        .HasColumnType("TEXT");

                    b.HasKey("Id_Pole");

                    b.ToTable("Poles");
                });

            modelBuilder.Entity("BackendAPP.Models.Technologie", b =>
                {
                    b.Property<long>("Id_techno")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("libelle")
                        .HasColumnType("TEXT");

                    b.HasKey("Id_techno");

                    b.ToTable("technologies");
                });

            modelBuilder.Entity("BackendAPP.Models.Thematique", b =>
                {
                    b.Property<long>("Id_thematique")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("image")
                        .HasColumnType("TEXT");

                    b.Property<string>("libelle")
                        .HasColumnType("TEXT");

                    b.HasKey("Id_thematique");

                    b.ToTable("thematiques");
                });

            modelBuilder.Entity("BackendAPP.Models.ClientThematique", b =>
                {
                    b.HasOne("BackendAPP.Models.Client", "client")
                        .WithMany()
                        .HasForeignKey("Id_Client")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendAPP.Models.Thematique", "thematique")
                        .WithMany()
                        .HasForeignKey("thematiqueId_thematique");

                    b.Navigation("client");

                    b.Navigation("thematique");
                });
#pragma warning restore 612, 618
        }
    }
}
